"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { CHAIN_LABEL, LEGAL_BASIS } from "@/lib/format";
import type { Chain } from "@/lib/generated/prisma/client";
import { Check, Copy, Send } from "lucide-react";

function buildEmailDraft({
  caseId,
  vaspName,
  address,
  chain,
  evidenceTrail,
}: {
  caseId: string;
  vaspName: string;
  address: string;
  chain: Chain;
  evidenceTrail: string[];
}) {
  const subject = `Disclosure Request — Case ${caseId} — ${vaspName}`;
  const body = `To: ${vaspName} Compliance / Legal Team

This is a disclosure request in relation to a law-enforcement investigation
under ${LEGAL_BASIS}.

Suspect address: ${address}
Chain: ${CHAIN_LABEL[chain]}
Case reference: ${caseId}

We request account-holder KYC details and transaction records associated
with the above address, or any address that received funds traced from it,
per the evidence trail below.

Evidence trail (transaction hashes):
${evidenceTrail.length > 0 ? evidenceTrail.map((h) => `- ${h}`).join("\n") : "(no evidence hashes recorded for this trace)"}

Please respond to this request at your earliest convenience.

— Generated by VASPtrace. This is a simulated disclosure-request draft —
Sahyog API access is not yet publicly available. Review before sending
through your organization's own official channel.`;
  return { subject, body };
}

export function SahyogButton({
  caseId,
  vaspName,
  alreadyRouted,
  address,
  chain,
  evidenceTrail,
}: {
  caseId: string;
  vaspName: string;
  alreadyRouted: boolean;
  address: string;
  chain: Chain;
  evidenceTrail: string[];
}) {
  const [loading, setLoading] = useState(false);
  const [payload, setPayload] = useState<unknown>(null);
  const [error, setError] = useState<string | null>(null);
  const [warning, setWarning] = useState<string | null>(null);
  const [routed, setRouted] = useState(alreadyRouted);
  const [copied, setCopied] = useState(false);

  async function route() {
    setLoading(true);
    setError(null);
    setWarning(null);
    try {
      const res = await fetch(`/api/cases/${caseId}/sahyog`, { method: "POST" });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error ?? "Routing failed");
      setPayload(data.payload);
      setRouted(true);
      if (data.warning) setWarning(data.warning); // non-fatal (e.g. n8n unreachable) — routing still succeeded
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setLoading(false);
    }
  }

  async function copyEmailDraft() {
    const { subject, body } = buildEmailDraft({ caseId, vaspName, address, chain, evidenceTrail });
    try {
      await navigator.clipboard.writeText(`Subject: ${subject}\n\n${body}`);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // clipboard API can be unavailable (permissions, insecure context) —
      // fail quietly rather than throwing; the button just doesn't confirm.
    }
  }

  return (
    <div className="flex flex-col gap-3">
      <div className="flex flex-wrap items-center gap-2">
        <Button onClick={route} disabled={loading} variant={routed ? "outline" : "default"}>
          <Send className="size-4" />
          {loading ? "Routing…" : routed ? `Re-route to ${vaspName}` : `Route disclosure request to ${vaspName}`}
        </Button>
        <Button onClick={copyEmailDraft} variant="outline">
          {copied ? <Check className="size-4" /> : <Copy className="size-4" />}
          {copied ? "Copied" : "Copy email draft"}
        </Button>
        <Badge
          variant="outline"
          className="whitespace-normal border-amber-700 text-amber-700 dark:border-amber-400 dark:text-amber-400"
        >
          Simulated integration — Sahyog API access not publicly available
        </Badge>
      </div>
      {error && <p className="text-sm text-destructive">{error}</p>}
      {warning && <p className="text-sm text-muted-foreground">{warning}</p>}
      {payload !== null && (
        <pre className="glass-panel max-h-64 overflow-auto p-3 text-xs">{JSON.stringify(payload, null, 2)}</pre>
      )}
    </div>
  );
}
